name: kml
channels:
  - rapidsai
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # - cudf
  # - cudatoolkit
  - biopython
  - scikit-learn
  - numpy
  - pandas
  - setuptools
  - psutil
  - ipykernel
  - matplotlib
  - seaborn
  - pyspark
  - pip
  - pip:
    - -e .